GroupMenu.Constants = {

    MENU_NAME_DISPLAY_OPTION_CHARACTER = 1,
    MENU_NAME_DISPLAY_OPTION_ACCOUNT = 2,

    INDEX_CROWN = 1,
    INDEX_NAME_ORIGINAL = 2,
    INDEX_INDEX = 3,
    INDEX_NAME = 4,
    INDEX_ZONE = 5,
    INDEX_CLASS = 6,
    INDEX_LEVEL = 7,
    INDEX_CHAMPIONICON = 8,
    INDEX_ROLE = 9,
    INDEX_CP = 10,
    INDEX_ALLIANCE = 11,
    INDEX_ALLIANCERANK = 12,
    INDEX_RACE = 13,
    INDEX_GENDER = 14,
    INDEX_SOCIAL = 15

}
