GroupMenu.Constants = {
    MENU_NAME_DISPLAY_OPTION_CHARACTER = 1,
    MENU_NAME_DISPLAY_OPTION_ACCOUNT = 2,
    COLUMN_INDEX_CP = 1,
    COLUMN_INDEX_ALLIANCE = 2,
    COLUMN_INDEX_ALLIANCE_RANK = 3,
    COLUMN_INDEX_RACE = 4,
    COLUMN_INDEX_GENDER = 5,
    COLUMN_INDEX_SOCIAL = 6
}
